// Standard Arabic-101 (Windows Arabic) keyboard layout, by physical row.
// Each entry is the character produced unshifted / with Shift.
export type ArabicKeyDef = { base: string; shift: string };

export const ARABIC_KEYBOARD_ROWS: ArabicKeyDef[][] = [
  [
    { base: "ذ", shift: "ّ" },
    { base: "١", shift: "!" },
    { base: "٢", shift: "@" },
    { base: "٣", shift: "#" },
    { base: "٤", shift: "$" },
    { base: "٥", shift: "%" },
    { base: "٦", shift: "^" },
    { base: "٧", shift: "&" },
    { base: "٨", shift: "*" },
    { base: "٩", shift: ")" },
    { base: "٠", shift: "(" },
    { base: "-", shift: "_" },
    { base: "=", shift: "+" },
  ],
  [
    { base: "ض", shift: "َ" },
    { base: "ص", shift: "ً" },
    { base: "ث", shift: "ُ" },
    { base: "ق", shift: "ٌ" },
    { base: "ف", shift: "لإ" },
    { base: "غ", shift: "إ" },
    { base: "ع", shift: "‘" },
    { base: "ه", shift: "÷" },
    { base: "خ", shift: "×" },
    { base: "ح", shift: "؛" },
    { base: "ج", shift: "<" },
    { base: "د", shift: ">" },
  ],
  [
    { base: "ش", shift: "ِ" },
    { base: "س", shift: "ٍ" },
    { base: "ي", shift: "]" },
    { base: "ب", shift: "[" },
    { base: "ل", shift: "لأ" },
    { base: "ا", shift: "أ" },
    { base: "ت", shift: "ـ" },
    { base: "ن", shift: "،" },
    { base: "م", shift: "/" },
    { base: "ك", shift: ":" },
    { base: "ط", shift: "\"" },
  ],
  [
    { base: "ئ", shift: "~" },
    { base: "ء", shift: "ْ" },
    { base: "ؤ", shift: "}" },
    { base: "ر", shift: "{" },
    { base: "لا", shift: "لآ" },
    { base: "ى", shift: "آ" },
    { base: "ة", shift: "'" },
    { base: "و", shift: "," },
    { base: "ز", shift: "." },
    { base: "ظ", shift: "؟" },
  ],
];
